# Staging values for node-hello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: staging

nginx:
  name: nginx
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
     
node:
  name: node
  image:
    repository: evfurman/node-hello
    tag: staging
    pullPolicy: Always
